# This file is generated and should not be modified directly.
# Edit 'scripts/generate_gitlab_yaml.sh' instead

stages:
  - verify-gitlab-yml
  - test

before_script:
  - date && date -u

verify-gitlab-yml:
  stage: verify-gitlab-yml
  image: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17
  script: 
    - source environment
    - make verify-gitlab-yml

.notebook-test:
  stage: test
  image: $IMAGE
  before_script:
    - mkdir -p ~/.config/gcloud
    - cp $TEST_MULE_CREDENTIALS ~/.config/gcloud/application_default_credentials.json
    - source environment
    - if [[ -e notebooks/$NOTEBOOK/leo_config ]]; then source notebooks/$NOTEBOOK/leo_config; fi
    - $LEO_PIP install --upgrade -r requirements-dev.txt
    - $LEO_PIP install --upgrade -r notebooks/$NOTEBOOK/requirements.txt
  script:
    - make lint/$NOTEBOOK
    - make mypy/$NOTEBOOK
    - make cicd_test/$NOTEBOOK

GWAS_blood_pressure_p1:
  extends: .notebook-test
  variables:
    NOTEBOOK: "GWAS_blood_pressure_p1"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

GWAS_blood_pressure_p2:
  extends: .notebook-test
  variables:
    NOTEBOOK: "GWAS_blood_pressure_p2"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

byod:
  extends: .notebook-test
  variables:
    NOTEBOOK: "byod"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

prepare_igv_viewer_input:
  extends: .notebook-test
  variables:
    NOTEBOOK: "prepare_igv_viewer_input"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

vcf_merge_subsample_tutorial:
  extends: .notebook-test
  variables:
    NOTEBOOK: "vcf_merge_subsample_tutorial"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

workflow_cost_estimator:
  extends: .notebook-test
  variables:
    NOTEBOOK: "workflow_cost_estimator"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-gatk:1.0.12

xvcfmerge_array_input:
  extends: .notebook-test
  variables:
    NOTEBOOK: "xvcfmerge_array_input"
    IMAGE: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17
