# This file is generated and should not be modified directly.
# Edit 'scripts/generate_gitlab_yaml.sh' instead

image: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

stages:
  - verify-gitlab-yml
  - test

before_script:
  - date && date -u

verify-gitlab-yml:
  stage: verify-gitlab-yml
  script: 
    - source environment
    - make verify-gitlab-yml

.notebook-test:
  stage: test
  before_script:
    - mkdir -p ~/.config/gcloud
    - cp $TEST_MULE_CREDENTIALS ~/.config/gcloud/application_default_credentials.json
    - source environment
    - $LEO_PIP install --upgrade -r requirements-dev.txt

byod:
  extends: .notebook-test
  script: make cicd_test/byod

picsure_01_api:
  extends: .notebook-test
  script: make cicd_test/picsure_01_api

prepare_igv_viewer_input:
  extends: .notebook-test
  script: make cicd_test/prepare_igv_viewer_input

vcf_merge_subsample_tutorial:
  extends: .notebook-test
  script: make cicd_test/vcf_merge_subsample_tutorial

workflow_cost_estimator:
  extends: .notebook-test
  script: make cicd_test/workflow_cost_estimator

xvcfmerge_array_input:
  extends: .notebook-test
  script: make cicd_test/xvcfmerge_array_input
