image: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.12

stages:
  - test

before_script:
  - date && date -u

byod:
  stage: test
  script:
    - . /home/jupyter-user/miniconda/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - mkdir -p ~/.config/gcloud
    - cp $TEST_MULE_CREDENTIALS ~/.config/gcloud/application_default_credentials.json
    - unset GOOGLE_APPLICATION_CREDENTIALS; export GOOGLE_PROJECT=firecloud-cgl; export WORKSPACE_NAME=terra-notebook-utils-tests
    - make cicd_notebooks/byod.py

prepare_igv_viewer_input:
  stage: test
  script:
    - . /home/jupyter-user/miniconda/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - export GOOGLE_APPLICATION_CREDENTIALS=$TEST_MULE_CREDENTIALS
    - make cicd_notebooks/prepare_igv_viewer_input.py

vcf_merge_subsample_tutorial:
  stage: test
  script:
    - . /home/jupyter-user/miniconda/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - export GOOGLE_APPLICATION_CREDENTIALS=$TEST_MULE_CREDENTIALS
    - make cicd_notebooks/vcf_merge_subsample_tutorial.py

xvcfmerge-array-input:
  stage: test
  script:
    - . /home/jupyter-user/miniconda/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - export GOOGLE_APPLICATION_CREDENTIALS=$TEST_MULE_CREDENTIALS
    - make cicd_notebooks/xvcfmerge_array_input.py
