image: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

stages:
  - test

before_script:
  - date && date -u

notebooks:
  stage: test
  before_script:
    - export PATH=/home/jupyter-user/.local/bin:$PATH
    - unset PIP_USER
    - mkdir -p ~/.config/gcloud
    - cp $TEST_MULE_CREDENTIALS ~/.config/gcloud/application_default_credentials.json
    - source environment
    - $LEO_PYTHON -m venv ~/venv
    - source ~/venv/bin/activate
    - pip install -r requirements-dev.txt
  script:
    - make test-cicd
