image: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.17

stages:
  - test

before_script:
  - date && date -u

notebooks:
  stage: test
  script:
    - . /home/jupyter-user/miniconda/bin/activate
    - pip install --no-cache-dir -r requirements-dev.txt
    - mkdir -p ~/.config/gcloud
    - cp $TEST_MULE_CREDENTIALS ~/.config/gcloud/application_default_credentials.json
    - for i in notebooks/*.py; do make cicd_"$i"; done
